import React, { useEffect, useRef, useState } from 'react';
import Head from 'next/head';

import Topnav from '@/components/Topnav';
import Footer from '@/components/Footer';

import { gsap, CSSPlugin} from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(CSSPlugin, ScrollTrigger)

import { Swiper, SwiperSlide } from 'swiper/react';

import { FaMapMarked, FaClock, FaPhoneAlt } from "react-icons/fa";

export default function Home() {
  const root = useRef();
  const root02 = useRef();
  const root03 = useRef();
  const root04 = useRef();
  const root05 = useRef();
  const root06 = useRef();
  const root07 = useRef();

  const branch = ['Branch Shop 1', 'Branch Shop 2', 'Branch Shop 3'];
  const [tab, setTab] = useState(branch[0]);

  console.log(tab);

  useEffect(() => {
    let ctx = gsap.fromTo(".img-height", { paddingTop: '0' }, { paddingTop: '120%' })
    return () => ctx.revert();
  }, []);

  useEffect(() => {
    let ctx = gsap.fromTo(".img-width", 1,{ width: '0' }, { width: '100%' })
    return () => ctx.revert();
  }, []);

  useEffect(() => {
    let ctx = gsap.timeline({
      scrollTrigger: {
        trigger: root.current,
        start: "top",
        end: "bottom",
        scrub: true
      }
    })
    .to(".fade-down", { y: -100, opacity: 0 })
    return () => ctx.revert();
  }, []);

  useEffect(() => {
    let ctx = gsap.timeline({
      scrollTrigger: {
        trigger: root03.current,
        start: "top",
        end: "bottom",
        scrub: true
      }
    })
    .to(".fade-up", { y: -70, opacity: 1 })
    return () => ctx.revert();
  }, []);

  useEffect(() => {
    let ctx = gsap.timeline({
      scrollTrigger: {
        trigger: root04.current,
        start: "top",
        end: "bottom",
        scrub: true
      }
    })
    .to(".card-down-02", { y: 50 })
    return () => ctx.revert();
  }, []);

  useEffect(() => {
    let ctx = gsap.timeline({
      scrollTrigger: {
        trigger: root05.current,
        start: "top",
        end: "bottom",
        scrub: true
      }
    })
    .to(".card-down-03", { y: 50 })

    return () => ctx.revert();
  }, []);

  useEffect(() => {
    let ctx = gsap.timeline({
      scrollTrigger: {
        trigger: root02.current,
        start: "top",
        end: "bottom",
        scrub: true
      }
    })
    .to(".card-down", { y: 50 })
    .to(".fade-up", { y: -70, opacity: 1 })
    return () => ctx.revert();
  }, []);

  useEffect(() => {
    let ctx = gsap.timeline({
      scrollTrigger: {
        trigger: root06.current,
        start: "top",
        end: "top",
        scrub: true
      }
    })
    .to(".card-down-04", { y: 50 })
    return () => ctx.revert();
  }, []);

  useEffect(() => {
    let ctx = gsap.timeline({
      scrollTrigger: {
        trigger: root07.current,
        start: "top",
        end: "bottom",
        scrub: true
      }
    })
    .to(".text-intro", { translateX: -250 })
    return () => ctx.revert();
  }, []);

  return (
    <>
      <Head>
        <title>Website Coffee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Topnav />

        <section className="section-padding section-01 bg-black" ref={root}>
          <div className="container max-w-full">
            <div className="grid grid-cols-12 flex-row-reverse">
              <div className="md:col-span-5 sm:col-span-8 col-span-12">
                <div className="relative">
                  <div className="ss-card ss-card-01">
                    <div className="ss-img no-hover vertical img-height">
                      <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-01.jpg')`}}></div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="md:col-span-7 sm:col-span-12 col-span-12 z-10 flex flex-col h-full">
                <div className="flex">
                  <div>
                    <h1 className="fade-down uppercase color-white font-semibold whitespace-nowrap">
                      Coffee Makes<br/>
                    </h1>
                    <p className="fade-down h1 font-bebas uppercase color-white font-semibold">
                      Severe, And Grave
                    </p>
                  </div>
                </div>
                <div className="detail-container">
                  <div className="detail-items">
                    <div className="detail-item">
                      <div className="icon">
                        <FaMapMarked />
                      </div>
                      <div className="text">
                        <p className="uppercase color-white font-light tracking-wider">
                          Location Lake House, 13 Hanway,<br/>
                          Square, London, England
                        </p>
                      </div>
                    </div>
                    <div className="detail-item mt-9">
                      <div className="icon">
                        <FaClock />
                      </div>
                      <div className="text">
                        <p className="uppercase color-white font-light tracking-wider">
                          Sun-Thu: 12PM - 6PM<br/>
                          Fri-Sat: 12PM - 8PM
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="section-padding bg-black" ref={root05}>
          <div className="container max-w-full">
            <div className="grid grid-cols-12">
              <div className="md:col-span-5 sm:col-span-6 col-span-12">
                <div className="flex justify-center items-center h-full">
                  <div className="ss-text text-center">
                    <p className="h4 font-oswald title">
                      SERVING TASTY<br/> COFFEE SINCE 2023
                    </p>
                  </div>
                </div>
              </div>
              <div className="md:col-span-7 sm:col-span-6 col-span-12">
                <div className="relative">
                  <div className="ss-card ss-card-02 img-width card-down-03">
                    <div className="ss-img no-hover">
                      <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-02.jpg')`}}></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="section-padding bg-black section-02" ref={root03}>
          <div className="container max-w-full">
            <div className="grid grid-cols-12">
              <div className="lg:col-span-7 md:col-span-12 col-span-12">
                <div className="relative card-down h-full">
                  <div className="ss-card ss-card-03 ">
                    <div className="ss-img no-hover vertical-02">
                      <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-03.jpg')`}}></div>
                    </div>
                  </div>
                  <div className="ss-card ss-card-04">
                    <div className="ss-img no-hover vertical-02">
                      <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-04.jpg')`}}></div>
                    </div>
                  </div>
                  <div className="title-intro fade-up">
                    <h1 className="color-white whitespace-nowrap uppercase font-bold">Makes Us<br/>Serve</h1>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-5 md:col-span-12 col-span-12">
                <div className="text-container">
                  <div className="wrapper">
                    <h4 className="font-semibold color-p uppercase lg-no-br ss-title-line-left">
                      Coffee is the best thing<br/>
                      to douse the sunrise with
                    </h4>
                    <p className="color-01 mt-7 leading-8">
                      Exercitation photo booth stumptown tote bag Banksy, 
                      elit small batch freegan sed. Craft beer elit seitan exercitation, 
                      photo booth et 8-bit kale chips proident chillwave deep v laborum. 
                      Aliquip veniam delectus, Marfa eiusmod Pinterest in do umami readymade 
                      swag. Selfies iPhone Kickstarter, drinking vinegar jean vinegar stumptown 
                      yr pop-up artisan.
                    </p>
                    <p className="color-01 mt-7 leading-8">
                      Meh synth Schlitz, tempor duis single-origin coffee ea next 
                      level ethnic fingerstache fanny pack nostrud. Photo booth anim 
                      8-bit hella, PBR 3 wolf moon beard Helvetica. 
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="section-padding section-03 bg-black" ref={root04}>
          <div className="container max-w-full">
            <div className="grid grid-cols-12">
              <div className="lg:col-span-6 md:col-span-5 col-span-12">
                <div className="mt-32">
                  <div className="ss-title-line-right">
                    <h4 className="font-semibold color-p uppercase">
                      Menus
                    </h4>  
                    <div className="line"></div>
                  </div>
                </div>
                <div className="relative">
                  <div className="pattern">
                    <div className="wrapper">
                      <img src="assets/img/pattern/01.png" />
                    </div>
                  </div>
                  <div className="ss-card ss-card-05 card-down-02">
                    <div className="ss-img no-hover vertical">
                      <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-05.jpg')`}}></div>
                    </div>
                  </div>
                  <div className="ss-card ss-card-06 card-down-02">
                    <div className="ss-img no-hover vertical-02">
                      <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-08.jpg')`}}></div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-6 md:col-span-7 col-span-12">
                <div className="food-menu-container mt-32">
                  <div className="wrapper">
                    <div className="food-menu-img">
                      <img src="assets/img/content/cup-01.jpg" alt="CUP IMAGE" />
                    </div>
                    <div className="food-menu-content">
                      <div className="wrapper">
                        <div className="title">
                          <h5 className="uppercase color-white font-medium">
                            Cafe Americano
                          </h5>
                        </div>
                        <div className="line"></div>
                        <div className="price">
                          <h6 className="color-p font-semibold">฿125</h6>
                        </div>
                      </div>
                      <p className="color-white">Espresso shots topped with hot water</p>
                    </div>
                  </div>
                </div>
                <div className="food-menu-container mt-8">
                  <div className="wrapper">
                    <div className="food-menu-img">
                      <img src="assets/img/content/cup-02.jpg" alt="CUP IMAGE" />
                    </div>
                    <div className="food-menu-content">
                      <div className="wrapper">
                        <div className="title">
                          <h5 className="uppercase color-white font-medium">
                            Cappuccino
                          </h5>
                        </div>
                        <div className="line"></div>
                        <div className="price">
                          <h6 className="color-p font-semibold">฿99</h6>
                        </div>
                      </div>
                      <p className="color-white">Espresso shots topped with hot water</p>
                    </div>
                  </div>
                </div>
                <div className="food-menu-titile mt-8">
                  <p className="color-white uppercase font-semibold">Classic</p>
                </div>
                <div className="food-menu-container active">
                  <div className="wrapper">
                    <div className="food-menu-img">
                      <img src="assets/img/content/cup-03.jpg" alt="CUP IMAGE" />
                    </div>
                    <div className="food-menu-content">
                      <div className="wrapper">
                        <div className="title">
                          <h5 className="uppercase color-white font-medium">
                            Espresso
                          </h5>
                        </div>
                        <div className="line"></div>
                        <div className="price">
                          <h6 className="color-p font-semibold">฿99</h6>
                        </div>
                      </div>
                      <p className="color-white">Espresso shots topped with hot water</p>
                    </div>
                  </div>
                </div>
                <div className="food-menu-container mt-8">
                  <div className="wrapper">
                    <div className="food-menu-img">
                      <img src="assets/img/content/cup-04.jpg" alt="CUP IMAGE" />
                    </div>
                    <div className="food-menu-content">
                      <div className="wrapper">
                        <div className="title">
                          <h5 className="uppercase color-white font-medium">
                            Caramel Macchiato
                          </h5>
                        </div>
                        <div className="line"></div>
                        <div className="price">
                          <h6 className="color-p font-semibold">฿99</h6>
                        </div>
                      </div>
                      <p className="color-white">Espresso shots topped with hot water</p>
                    </div>
                  </div>
                </div>
                <div className="food-menu-container mt-8">
                  <div className="wrapper">
                    <div className="food-menu-img">
                      <img src="assets/img/content/cup-05.jpg" alt="CUP IMAGE" />
                    </div>
                    <div className="food-menu-content">
                      <div className="wrapper">
                        <div className="title">
                          <h5 className="uppercase color-white font-medium">
                            Cafe Mocha
                          </h5>
                        </div>
                        <div className="line"></div>
                        <div className="price">
                          <h6 className="color-p font-semibold">฿99</h6>
                        </div>
                      </div>
                      <p className="color-white">Espresso shots topped with hot water</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="section-padding section-04">
          <div className="container max-w-full">
            <div className="grid grid-cols-12">
              <div className="lg:col-span-7 md:col-span-12 col-span-12">
                <div className="relative">
                  <div className="ss-card ss-card-07 ">
                    <div className="ss-img no-hover card-down-04">
                      <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-06.jpg')`}}></div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-5 md:col-span-12 col-span-12">
                <div className="logo">
                  <img src="assets/img/logo/01.png" />
                </div>
                <h4 className="font-semibold color-p uppercase lg-no-br ss-title-line-left mt-6">
                  Intro
                </h4>
                <p className="color-01 mt-5 leading-8">
                  Exercitation photo booth stumptown tote bag Banksy, 
                  elit small batch freegan sed. Craft beer elit seitan exercitation, 
                  photo booth et 8-bit kale chips proident chillwave deep v laborum. 
                  Aliquip veniam delectus, Marfa eiusmod Pinterest in do umami readymade 
                  swag. Selfies iPhone Kickstarter, drinking vinegar jean vinegar stumptown 
                  yr pop-up artisan.
                </p>
                <p className="color-01 mt-7 leading-8">
                  Meh synth Schlitz, tempor duis single-origin coffee ea next 
                  level ethnic fingerstache fanny pack nostrud. Photo booth anim 
                  8-bit hella, PBR 3 wolf moon beard Helvetica. 
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="section-padding">
          <div className="container">
            <div className="jc-start ss-title-line-right mt-5">
              <h4 className="font-semibold color-p uppercase">
                Gallery
              </h4>  
              <div className="line"></div>
            </div>
          </div>
         
          <Swiper className="swiper-01"
             slidesPerView={3}
             breakpoints={{ 
              0: { slidesPerView: 1 },
              576: { slidesPerView: 2 },
              768: { slidesPerView: 3, spaceBetween:40},
            }} 
            >
            <SwiperSlide>
              <div className="ss-card">
                <div className="ss-img">
                  <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-07.jpg')`}}></div>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className="ss-card">
                <div className="ss-img">
                  <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-09.jpg')`}}></div>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className="ss-card">
                <div className="ss-img">
                  <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-10.jpg')`}}></div>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className="ss-card">
                <div className="ss-img">
                  <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-11.jpg')`}}></div>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className="ss-card">
                <div className="ss-img">
                  <div className="img-bg" style={{backgroundImage:`url('assets/img/content/img-12.jpg')`}}></div>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>
        </section>

        <section className="section-padding section-07" ref={root07}>
          <div className="tab-container">
            <div className="text-intro">CONTACT US</div>
             <div className="container max-w-full">
              <div className="grid grid-cols-12">
                <div className="lg:col-span-4 md:col-span-6 col-span-12">
                  <div className="tabs tabs-01">
                    {branch.map((data, i) => (
                    <div key={`tab_${i}`} onClick={e => { e.preventDefault(); setTab(data);}} 
                    className={`tab ${tab === data? 'active': ''}`}>{data}</div>
                    ))}
                  </div>
                  <form className="form-container">
                    <div className="jc-start ss-title-line-right mt-5">
                      <h4 className="font-semibold color-p uppercase">
                        Contact
                      </h4>  
                      <div className="line"></div>
                    </div>
                    <div className="tab-contents">
                      {branch.map((data, i) => (
                        <div key={`tabc_${i}`} className={`tab-content ${tab === data? 'active' : ''}`}>
                          {tab === 'Branch Shop 1'?(
                            <div className="contact-list mt-4">
                              <div className="contact-item">
                                <div className="icon">
                                  <FaMapMarked />
                                </div>
                                <div className="text">
                                  <p className="leading-8">
                                    No. 84/52 Soi Pongnaresorn Village, Hua Hin 
                                    Subdistrict, Hua Hin District 77110
                                  </p>
                                </div>
                              </div>
                              <div className="contact-item">
                                <div className="icon">
                                  <FaPhoneAlt />
                                </div>
                                <div className="text">
                                  <p>
                                    095 629 2916
                                  </p>
                                </div>
                              </div>
                            </div>
                          ):(<></>)}
                          {tab === 'Branch Shop 2'?(
                            <div className="contact-list mt-4">
                              <div className="contact-item">
                                <div className="icon">
                                  <FaMapMarked />
                                </div>
                                <div className="text">
                                  <p className="leading-8">
                                    497 Moo 9, Soi Sermsuk, Hin Lek Fai Subdistrict, 
                                    Hua Hin District 77110
                                  </p>
                                </div>
                              </div>
                              <div className="contact-item">
                                <div className="icon">
                                  <FaPhoneAlt />
                                </div>
                                <div className="text">
                                  <p>
                                    095 629 2916
                                  </p>
                                </div>
                              </div>
                            </div>
                          ):(<></>)}
                          {tab === 'Branch Shop 3'?(
                            <div className="contact-list mt-4">
                              <div className="contact-item">
                                <div className="icon">
                                  <FaMapMarked />
                                </div>
                                <div className="text">
                                  <p className="leading-8">
                                    83 12-13 Petchkasem Road, Hua Hin Subdistrict, Hua 
                                    Hin District, Prachuap Khiri Khan 77110
                                  </p>
                                </div>
                              </div>
                              <div className="contact-item">
                                <div className="icon">
                                  <FaPhoneAlt />
                                </div>
                                <div className="text">
                                  <p>
                                    095 629 2916
                                  </p>
                                </div>
                              </div>
                            </div>
                          ):(<></>)}
                        </div>
                      ))}  
                    </div>
                  </form>
                </div>
                <div className="lg:col-span-8 md:col-span-6 col-span-12">
                  <div className="tab-contents">
                    {branch.map((data, i) => (
                      <div key={`tabc_${i}`} className={`tab-content ${tab === data? 'active' : ''}`}>
                        {tab === 'Branch Shop 1'?(
                          <iframe className="map-container" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3893.413906442111!2d99.938316!3d12.6208296!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30fd0183dca2fc41%3A0x9d5d60ff5a8d079f!2z4LiB4Lij4Liw4Lib4Li44LiB4Lii4LiyIOC4hOC4suC5gOC4n-C5iA!5e0!3m2!1sth!2sth!4v1690641950338!5m2!1sth!2sth" 
                          width='100%' height={450} style={{border: 0}} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" />
                        ):(<></>)}
                        {tab === 'Branch Shop 2'?(
                          <iframe className="map-container" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3894.2601476427726!2d99.881306!3d12.5650904!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30fdab8effacf68f%3A0x671fe13cb29c6afa!2z4LiB4Lij4Liw4Lib4Li44LiB4Lii4Liy4LiE4Liy4LmA4Lif4LmIIHgg4Lij4LmI4Lih4Lij4Li34LmI4LiZ4LmB4LiE4Lih4Lib4LmM!5e0!3m2!1sth!2sth!4v1690701592803!5m2!1sth!2sth" 
                          width='100%' height={450} style={{border: 0}} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" />
                        ):(<></>)}
                        {tab === 'Branch Shop 3'?(
                            <iframe className="map-container" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d486.78047343011343!2d99.958326!3d12.5661703!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30fdabb1c0ee8ae9%3A0x60cab20222ff4918!2z4LiB4Liy4LiZ4LiV4LmM4LmA4Lib4LmH4LiU4LiV4Li44LmL4LiZIOC4q-C4seC4p-C4q-C4tOC4mQ!5e0!3m2!1sth!2sth!4v1690701700610!5m2!1sth!2sth" 
                            width='100%' height={450} style={{border: 0}} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" />
                        ):(<></>)}
                      </div>
                    ))}     
                  </div>
                </div>
              </div>
            </div>  
          </div>
        </section>

        <section className="section-05" ref={root06}>
          <div className="since card-down-04" >
            <div className="wrapper">
              <p className="h5 color-white fw-200">since</p>
              <h4 className="color-white fw-600">2023</h4>
              <div className="cup-container">
                <img src="assets/img/icon/svg/grommet.svg" alt="Pattern Arrow" />
              </div>
            </div>
          </div>
          <div className="grid grid-cols-12">
            <div className="md:col-span-6 h-full col-span-12">
              <div className="content-left">
                <h4 className="font-semibold uppercase">History</h4>
                <p className="mt-6">
                  Craft beer elit seitan exercitation, photo booth et 8-bit 
                  kale chips proident chillwave deep v laborum. Aliquip veniam delectus, 
                  Marfa eiusmod Pinterest in do umami readymade swag.
                </p>
                <div className="signature">
                  <img src="assets/img/content/signature.png" alt="CUP IMAGE" />
                </div>
              </div>
            </div>
            <div className="md:col-span-6 col-span-12">
              <div className="content-right">
                <div className="img-bg" style={{backgroundImage:`url('assets/img/content/13.jpg')`}}></div> 
              </div>
            </div>
          </div>
        </section>

        <section className="section-padding section-06">
          <div className="container max-w-full">
            <div className="grid grid-cols-12">
              <div className="lg:col-span-4 md:col-span-6 col-span-12">
                <div className="content">
                  <div className="wrapper">
                    <div className="icon">
                      <img src="assets/img/icon/vintage_phone.png" alt="VINTAGE PHONE"/>
                    </div>
                    <div className="text">
                      <p>Opening Hours</p>
                      <p>11.30AM - 2.30PM</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-4 md:col-span-6 col-span-12">
                <div className="content">
                  <div className="wrapper">
                    <div className="icon">
                      <img src="assets/img/icon/vintage_compass.png" alt="VINTAGE COMPASS"/>
                    </div>
                    <div className="text">
                      <p>Location Lake House, 13 Hanway</p>
                      <p>Square, London, England</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:col-span-4 md:col-span-12 col-span-12">
                <div className="content">
                  <div className="wrapper">
                    <div className="social-list">
                      <div className="social-item">
                        <img src="assets/img/icon/svg/facebook.svg" alt="Fackbook"/>
                      </div>
                      <div className="social-item">
                        <img src="assets/img/icon/svg/instagram.svg" alt="Instagram"/>
                      </div>
                      <div className="social-item">
                        <img src="assets/img/icon/svg/twitter.svg" alt="Twitter"/>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </main>
    </>
  )
}
